
for i=1:numel(species)
    disp(['species(' num2str(i) ') = struct(''spec_id'',''' char(species(i).spec_id) ...
                  ''',''spec_name'',''' char(species(i).spec_name) ...
                  ''',''fbc_chemicalFormula'',''' char(species(i).fbc_chemicalFormula) ...
                  ''',''fbc_charge'',' num2str(species(i).fbc_charge) ')']);
end
for i=1:numel(reactions)
    disp(['reactions(' num2str(i) ') = struct(''reac_id'',''' reactions(i).reac ...
              ''',''equation'',''' reactions(i).equation ...
              ''',''lb'',' num2str(reactions(i).lb) ...
              ',''ub'',' num2str(reactions(i).ub) ...
              ',''fbc_geneProductAssociation'',''' reactions(i).fbc_geneProductAssociation ''')']);
end