function [prod_id,species,reactions] = load_pathway(product)
    switch product
        case  1 % ethanol
			prod_id = 'EX_etoh_e';
			species = [];
			reactions = [];
        case  2 % isobutanol
			prod_id      = 'EX_ibutoh_e';
			species(1)   = struct('spec_id','2mppal_c','spec_name','2-Methylpropanal','fbc_chemicalFormula','C4H8O','fbc_charge',0);
			species(2)   = struct('spec_id','ibutoh_c','spec_name','Isobutyl alcohol','fbc_chemicalFormula','C4H10O','fbc_charge',0);
			species(3)   = struct('spec_id','ibutoh_p','spec_name','Isobutyl alcohol','fbc_chemicalFormula','C4H10O','fbc_charge',0);
			species(4)   = struct('spec_id','ibutoh_e','spec_name','Isobutyl alcohol','fbc_chemicalFormula','C4H10O','fbc_charge',0);
			reactions(1) = struct('reac_id','3MOBDC','equation','1 3mob_c + 1 h_c = 1 co2_c + 1 2mppal_c','lb',0,'ub',1000,'fbc_geneProductAssociation','kivD');
			reactions(2) = struct('reac_id','ALCD23xi','equation','1 h_c + 1 nadh_c + 1 2mppal_c = 1 nad_c + 1 ibutoh_c','lb',0,'ub',1000,'fbc_geneProductAssociation','adh2');
			reactions(3) = struct('reac_id','IBUTOHtpp','equation','1 ibutoh_c = 1 ibutoh_p','lb',-1000,'ub',1000,'fbc_geneProductAssociation','');
			reactions(4) = struct('reac_id','IBUTOHtex','equation','1 ibutoh_p = 1 ibutoh_e','lb',-1000,'ub',1000,'fbc_geneProductAssociation','');
			reactions(5) = struct('reac_id','EX_ibutoh_e','equation','1 ibutoh_e =','lb',0,'ub',1000,'fbc_geneProductAssociation','');
        case  3 % 1,4-BDO
			prod_id      = 'EX_14bdo_e';
			species(1)   = struct('spec_id','4hb_c','spec_name','4-Hydroxybutanoate','fbc_chemicalFormula','C4H7O3','fbc_charge',-1);
			species(2)   = struct('spec_id','4hbcoa_c','spec_name','4-Hydroxybutyryl-CoA','fbc_chemicalFormula','C25H38N7O18P3S','fbc_charge',-4);
			species(3)   = struct('spec_id','4hbal_c','spec_name','4-Hydroxybutanal','fbc_chemicalFormula','C4H8O2','fbc_charge',0);
			species(4)   = struct('spec_id','14bdo_c','spec_name','Butane-1,4-diol','fbc_chemicalFormula','C4H10O2','fbc_charge',0);
			species(5)   = struct('spec_id','14bdo_p','spec_name','Butane-1,4-diol','fbc_chemicalFormula','C4H10O2','fbc_charge',0);
			species(6)   = struct('spec_id','14bdo_e','spec_name','Butane-1,4-diol','fbc_chemicalFormula','C4H10O2','fbc_charge',0);
			reactions(1) = struct('reac_id','SSCOARx','equation','1 h_c + 1 nadph_c + 1 succoa_c = 1 coa_c + 1 nadp_c + 1 sucsal_c','lb',0,'ub',1000,'fbc_geneProductAssociation','sucD_Pg');
			reactions(2) = struct('reac_id','AKGDC','equation','1 akg_c + 1 h_c = 1 co2_c + 1 sucsal_c','lb',0,'ub',1000,'fbc_geneProductAssociation','sucA_Mb');
			reactions(3) = struct('reac_id','4HBD','equation','1 h_c + 1 nadh_c + 1 sucsal_c = 1 4hb_c + 1 nad_c','lb',0,'ub',1000,'fbc_geneProductAssociation','4hbD_Pg');
			reactions(4) = struct('reac_id','4HBCT','equation','1 4hb_c + 1 accoa_c = 1 4hbcoa_c + 1 ac_c','lb',0,'ub',1000,'fbc_geneProductAssociation','cat2');
			reactions(5) = struct('reac_id','4HBDH','equation','1 4hbcoa_c + 1 h_c + 1 nadh_c = 1 4hbal_c + 1 coa_c + 1 nad_c','lb',0,'ub',1000,'fbc_geneProductAssociation','adh2');
			reactions(6) = struct('reac_id','4HBDx','equation','1 4hbal_c + 1 h_c + 1 nadh_c = 1 14bdo_c + 1 nad_c','lb',0,'ub',1000,'fbc_geneProductAssociation','adhE2');
			reactions(7) = struct('reac_id','14BDOtpp','equation','1 14bdo_c = 1 14bdo_p','lb',-1000,'ub',1000,'fbc_geneProductAssociation','');
			reactions(8) = struct('reac_id','14BDOtex','equation','1 14bdo_p = 1 14bdo_e','lb',-1000,'ub',1000,'fbc_geneProductAssociation','');
			reactions(9) = struct('reac_id','EX_14bdo_e','equation','1 14bdo_e =','lb',0,'ub',1000,'fbc_geneProductAssociation','');
        case  4 % 2,3-BDO
			prod_id      = 'EX_23bdo_e';
			species(1)   = struct('spec_id','actn_c','spec_name','3-Hydroxybutan-2-one','fbc_chemicalFormula','C4H8O2','fbc_charge',0);
			species(2)   = struct('spec_id','23bdo_c','spec_name','Butane-2,3-diol','fbc_chemicalFormula','C4H10O2','fbc_charge',0);
			species(3)   = struct('spec_id','23bdo_p','spec_name','Butane-2,3-diol','fbc_chemicalFormula','C4H10O2','fbc_charge',0);
			species(4)   = struct('spec_id','23bdo_e','spec_name','Butane-2,3-diol','fbc_chemicalFormula','C4H10O2','fbc_charge',0);
			reactions(1) = struct('reac_id','ACLDC','equation','1 alac__S_c + 1 h_c = 1 co2_c + 1 actn_c','lb',0,'ub',1000,'fbc_geneProductAssociation','aldA and aldC');
			reactions(2) = struct('reac_id','BTDD','equation','1 h_c + 1 nadh_c + 1 actn_c = 1 nad_c + 1 23bdo_c','lb',0,'ub',1000,'fbc_geneProductAssociation','butB');
			reactions(3) = struct('reac_id','23BDOtpp','equation','1 23bdo_c = 1 23bdo_p','lb',-1000,'ub',1000,'fbc_geneProductAssociation','');
			reactions(4) = struct('reac_id','23BDOtex','equation','1 23bdo_p = 1 23bdo_e','lb',-1000,'ub',1000,'fbc_geneProductAssociation','');
			reactions(5) = struct('reac_id','EX_23bdo_e','equation','1 23bdo_e =','lb',0,'ub',1000,'fbc_geneProductAssociation','');
        case  5 % itaconic acid
			prod_id = 'EX_itacon_e';
			species(1)   = struct('spec_id','itacon_c','spec_name','2-Methylenesuccinate','fbc_chemicalFormula','C5H4O4','fbc_charge',-2);
			species(2)   = struct('spec_id','itacon_p','spec_name','2-Methylenesuccinate','fbc_chemicalFormula','C5H4O4','fbc_charge',-2);
			species(3)   = struct('spec_id','itacon_e','spec_name','2-Methylenesuccinate','fbc_chemicalFormula','C5H4O4','fbc_charge',-2);
			reactions(1) = struct('reac_id','CADC','equation','1 h_c + 1 acon_C_c = 1 itacon_c + 1 co2_c','lb',0,'ub',1000,'fbc_geneProductAssociation','cadA');
			reactions(2) = struct('reac_id','ITACONtpp','equation','1 itacon_c = 1 itacon_p','lb',-1000,'ub',1000,'fbc_geneProductAssociation','');
			reactions(3) = struct('reac_id','ITACONtex','equation','1 itacon_p = 1 itacon_e','lb',-1000,'ub',1000,'fbc_geneProductAssociation','');
			reactions(4) = struct('reac_id','EX_itacon_e','equation','1 itacon_e =','lb',0,'ub',1000,'fbc_geneProductAssociation','');
        case  6 % tryptophane
			prod_id      = 'EX2_trp__L_e';
			species      = [];
			reactions(1) = struct('reac_id','EX2_trp__L_e','equation','1 trp__L_e =','lb',0,'ub',1000,'fbc_geneProductAssociation','');
        case  7 % lysine
			prod_id      = 'EX2_lys__L_e';
			species      = [];
			reactions(1) = struct('reac_id','EX2_lys__L_e','equation','1 lys__L_e =','lb',0,'ub',1000,'fbc_geneProductAssociation','');
        case  8 % glutamate
			prod_id      = 'EX2_glu__L_e';
			species      = [];
			reactions(1) = struct('reac_id','EX2_glu__L_e','equation','1 glu__L_e =','lb',0,'ub',1000,'fbc_geneProductAssociation','');
        case  9 % isoprene
			prod_id      = 'EX_is_e';
			species(1)   = struct('spec_id','hmgcoa_c','spec_name','3-Hydroxy-3-methyl-glutaryl-CoA','fbc_chemicalFormula','C27H39N7O20P3S','fbc_charge',-5);
			species(2)   = struct('spec_id','mev_c','spec_name','(3R)-3,5-Dihydroxy-3-methylpentanoate','fbc_chemicalFormula','C6H11O4','fbc_charge',-1);
			species(3)   = struct('spec_id','5pmev_c','spec_name','(3R)-3-Hydroxy-3-methyl-5-(phosphonooxy)pentanoate','fbc_chemicalFormula','C6H10O7P','fbc_charge',-3);
			species(4)   = struct('spec_id','5dpmev_c','spec_name','(3R)-3-Hydroxy-5-{[hydroxy(phosphonooxy)phosphoryl]oxy}-3-methylpentanoate','fbc_chemicalFormula','C6H10O10P2','fbc_charge',-4);
			species(5)   = struct('spec_id','is_c','spec_name','Isoprene','fbc_chemicalFormula','C5H8','fbc_charge',0);
			species(6)   = struct('spec_id','is_p','spec_name','Isoprene','fbc_chemicalFormula','C5H8','fbc_charge',0);
			species(7)   = struct('spec_id','is_e','spec_name','Isoprene','fbc_chemicalFormula','C5H8','fbc_charge',0);
			reactions(1) = struct('reac_id','HMGCOAS','equation','1 aacoa_c + 1 accoa_c + 1 h2o_c = 1 coa_c + 1 h_c + 1 hmgcoa_c','lb',-1000,'ub',1000,'fbc_geneProductAssociation','mvaS');
			reactions(2) = struct('reac_id','HMGCOAR','equation','2 h_c + 2 nadph_c + 1 hmgcoa_c = 1 coa_c + 2 nadp_c + 1 mev_c','lb',-1000,'ub',1000,'fbc_geneProductAssociation','mvaE');
			reactions(3) = struct('reac_id','MEVK1','equation','1 atp_c + 1 mev_c = 1 adp_c + 1 h_c + 1 5pmev_c','lb',0,'ub',1000,'fbc_geneProductAssociation','mvk');
			reactions(4) = struct('reac_id','PMEVK','equation','1 atp_c + 1 5pmev_c = 1 adp_c + 1 5dpmev_c','lb',0,'ub',1000,'fbc_geneProductAssociation','pmk');
			reactions(5) = struct('reac_id','DPMVD','equation','1 atp_c + 1 5dpmev_c = 1 adp_c + 1 co2_c + 1 ipdp_c + 1 pi_c','lb',0,'ub',1000,'fbc_geneProductAssociation','mvd');
			reactions(6) = struct('reac_id','ISS','equation','1 dmpp_c = 1 is_c + 1 ppi_c','lb',0,'ub',1000,'fbc_geneProductAssociation','IspS');
			reactions(7) = struct('reac_id','IStpp','equation','1 is_c = 1 is_p','lb',-1000,'ub',1000,'fbc_geneProductAssociation','');
			reactions(8) = struct('reac_id','IStex','equation','1 is_p = 1 is_e','lb',0,'ub',1000,'fbc_geneProductAssociation','');
			reactions(9) = struct('reac_id','EX_is_e','equation','1 is_e =','lb',0,'ub',1000,'fbc_geneProductAssociation','');
        case 10 % octyl acetate
			prod_id      = 'EX_ocac_e';
			species(1)   = struct('spec_id','octal_c','spec_name','octanal','fbc_chemicalFormula','C8H16O','fbc_charge',0);
			species(2)   = struct('spec_id','octoh_c','spec_name','octanol','fbc_chemicalFormula','C8H18O','fbc_charge',0);
			species(3)   = struct('spec_id','ocac_c','spec_name','octyl acetate','fbc_chemicalFormula','C10H20O2','fbc_charge',0);
			species(4)   = struct('spec_id','ocac_p','spec_name','octyl acetate (periplasm)','fbc_chemicalFormula','C10H20O2','fbc_charge',0);
			species(5)   = struct('spec_id','ocac_e','spec_name','octyl acetate (extracellular)','fbc_chemicalFormula','C10H20O2','fbc_charge',0);
			reactions(1) = struct('reac_id','CAR','equation','1 octa_c + nadph_c + h_c + atp_c = octal_c + nadp_c + amp_c + ppi_c','lb',0,'ub',1000,'fbc_geneProductAssociation','carholo');
			reactions(2) = struct('reac_id','AHR','equation','1 octal_c + nadph_c + h_c = 1 octoh_c + nadp_c','lb',0,'ub',1000,'fbc_geneProductAssociation','oahr');
			reactions(3) = struct('reac_id','AAT','equation','1 octoh_c + 1 accoa_c = 1 ocac_c + 1 coa_c','lb',0,'ub',1000,'fbc_geneProductAssociation','scatf1');
			reactions(4) = struct('reac_id','OCACtpp','equation','1 ocac_c = 1 ocac_p','lb',0,'ub',1000,'fbc_geneProductAssociation','');
			reactions(5) = struct('reac_id','OCACtex','equation','1 ocac_p = 1 ocac_e','lb',0,'ub',1000,'fbc_geneProductAssociation','');
			reactions(6) = struct('reac_id','EX_ocac_e','equation','1 ocac_e =','lb',0,'ub',1000,'fbc_geneProductAssociation','');
			reactions(7) = struct('reac_id','XPK','equation','1 xu5p__D_c + 1 pi_c = 1 actp_c + 1 g3p_c + 1 h2o_c','lb',0,'ub',1000,'fbc_geneProductAssociation','fxpk');
			reactions(8) = struct('reac_id','FPK','equation','1 f6p_c + 1 pi_c = 1 actp_c + 1 e4p_c + 1 h2o_c','lb',0,'ub',1000,'fbc_geneProductAssociation','fxpk');
        case 11 % butane
			prod_id      = 'EX_butane_e';
			species(1)   = struct('spec_id','ppoh_c','spec_name','','fbc_chemicalFormula','C3H8O1','fbc_charge',0);
			species(2)   = struct('spec_id','ppoh_p','spec_name','','fbc_chemicalFormula','C3H8O1','fbc_charge',0);
			species(3)   = struct('spec_id','ppoh_e','spec_name','','fbc_chemicalFormula','C3H8O1','fbc_charge',0);
			species(4)   = struct('spec_id','ethgly_c','spec_name','','fbc_chemicalFormula','C2H6O2','fbc_charge',0);
			species(5)   = struct('spec_id','ethgly_p','spec_name','','fbc_chemicalFormula','C2H6O2','fbc_charge',0);
			species(6)   = struct('spec_id','ethgly_e','spec_name','','fbc_chemicalFormula','C2H6O2','fbc_charge',0);
			species(7)   = struct('spec_id','ethox_c','spec_name','','fbc_chemicalFormula','C2H4O','fbc_charge',0);
			species(8)   = struct('spec_id','propane_c','spec_name','','fbc_chemicalFormula','C3H8','fbc_charge',0);
			species(9)   = struct('spec_id','ptal_c','spec_name','','fbc_chemicalFormula','C5H10O','fbc_charge',0);
			species(10)   = struct('spec_id','butane_c','spec_name','','fbc_chemicalFormula','C4H10','fbc_charge',0);
			species(11)   = struct('spec_id','hxal_c','spec_name','','fbc_chemicalFormula','C6H12O','fbc_charge',0);
			species(12)   = struct('spec_id','pentane_c','spec_name','','fbc_chemicalFormula','C5H12','fbc_charge',0);
			species(13)   = struct('spec_id','hptal_c','spec_name','','fbc_chemicalFormula','C7H14O','fbc_charge',0);
			species(14)   = struct('spec_id','hxane_c','spec_name','','fbc_chemicalFormula','C6H14','fbc_charge',0);
			species(15)   = struct('spec_id','octal_c','spec_name','','fbc_chemicalFormula','C8H16O','fbc_charge',0);
			species(16)   = struct('spec_id','heptane_c','spec_name','','fbc_chemicalFormula','C7H16','fbc_charge',0);
			species(17)   = struct('spec_id','nonal_c','spec_name','','fbc_chemicalFormula','C9H18O','fbc_charge',0);
			species(18)   = struct('spec_id','octane_c','spec_name','','fbc_chemicalFormula','C8H18','fbc_charge',0);
			species(19)   = struct('spec_id','dcal_c','spec_name','','fbc_chemicalFormula','C10H20O','fbc_charge',0);
			species(20)   = struct('spec_id','nonane_c','spec_name','','fbc_chemicalFormula','C9H20','fbc_charge',0);
			species(21)   = struct('spec_id','val_c','spec_name','','fbc_chemicalFormula','C5H9O2','fbc_charge',-1);
			species(22)   = struct('spec_id','hpta_c','spec_name','','fbc_chemicalFormula','C7H13O2','fbc_charge',-1);
			species(23)   = struct('spec_id','nonte_c','spec_name','','fbc_chemicalFormula','C9H17O2','fbc_charge',-1);
			species(24)   = struct('spec_id','ptcoa_c','spec_name','','fbc_chemicalFormula','C26H40N7O17P3S','fbc_charge',-4);
			species(25)   = struct('spec_id','hptcoa_c','spec_name','','fbc_chemicalFormula','C28H44N7O17P3S','fbc_charge',-4);
			species(26)   = struct('spec_id','noncoa_c','spec_name','','fbc_chemicalFormula','C30H48N7O17P3S','fbc_charge',-4);
			species(27)   = struct('spec_id','cis23dhbtcoa_c','spec_name','','fbc_chemicalFormula','C25H36N7O17P3S','fbc_charge',-4);
			species(28)   = struct('spec_id','cis2mctcoa_c','spec_name','','fbc_chemicalFormula','C26H38N7O17P3S','fbc_charge',-4);
			species(29)   = struct('spec_id','cis2hxncoa_c','spec_name','','fbc_chemicalFormula','C27H40N7O17P3S','fbc_charge',-4);
			species(30)   = struct('spec_id','cis2hpcoa_c','spec_name','','fbc_chemicalFormula','C28H42N7O17P3S','fbc_charge',-4);
			species(31)   = struct('spec_id','cis2noncoa_c','spec_name','','fbc_chemicalFormula','C30H46N7O17P3S','fbc_charge',-4);
			species(32)   = struct('spec_id','3hbcoa__R_c','spec_name','','fbc_chemicalFormula','C25H38N7O18P3S','fbc_charge',-4);
			species(33)   = struct('spec_id','3hptcoa_c','spec_name','','fbc_chemicalFormula','C26H40N7O18P3S','fbc_charge',-4);
			species(34)   = struct('spec_id','3hhcoa__R_c','spec_name','','fbc_chemicalFormula','C27H42N7O18P3S','fbc_charge',-4);
			species(35)   = struct('spec_id','3hpcoa__R_c','spec_name','','fbc_chemicalFormula','C28H44N7O18P3S','fbc_charge',-4);
			species(36)   = struct('spec_id','3hnoncoa__R_c','spec_name','','fbc_chemicalFormula','C30H48N7O18P3S','fbc_charge',-4);
			species(37)   = struct('spec_id','3oxptcoa_c','spec_name','','fbc_chemicalFormula','C26H38N7O18P3S','fbc_charge',-4);
			species(38)   = struct('spec_id','3oxhepcoa_c','spec_name','','fbc_chemicalFormula','C28H42N7O18P3S','fbc_charge',-4);
			species(39)   = struct('spec_id','3ononcoa_c','spec_name','','fbc_chemicalFormula','C30H46N7O18P3S','fbc_charge',-4);
			species(40)   = struct('spec_id','hxane_p','spec_name','','fbc_chemicalFormula','C6H14','fbc_charge',0);
			species(41)   = struct('spec_id','hxane_e','spec_name','','fbc_chemicalFormula','C6H14','fbc_charge',0);
			species(42)   = struct('spec_id','propane_p','spec_name','','fbc_chemicalFormula','C3H8','fbc_charge',0);
			species(43)   = struct('spec_id','propane_e','spec_name','','fbc_chemicalFormula','C3H8','fbc_charge',0);
			species(44)   = struct('spec_id','butane_p','spec_name','','fbc_chemicalFormula','C4H10','fbc_charge',0);
			species(45)   = struct('spec_id','butane_e','spec_name','','fbc_chemicalFormula','C4H10','fbc_charge',0);
			species(46)   = struct('spec_id','pentane_p','spec_name','','fbc_chemicalFormula','C5H12','fbc_charge',0);
			species(47)   = struct('spec_id','pentane_e','spec_name','','fbc_chemicalFormula','C5H12','fbc_charge',0);
			species(48)   = struct('spec_id','heptane_p','spec_name','','fbc_chemicalFormula','C7H16','fbc_charge',0);
			species(49)   = struct('spec_id','heptane_e','spec_name','','fbc_chemicalFormula','C7H16','fbc_charge',0);
			species(50)   = struct('spec_id','octane_p','spec_name','','fbc_chemicalFormula','C8H18','fbc_charge',0);
			species(51)   = struct('spec_id','octane_e','spec_name','','fbc_chemicalFormula','C8H18','fbc_charge',0);
			species(52)   = struct('spec_id','nonane_p','spec_name','','fbc_chemicalFormula','C9H20','fbc_charge',0);
			species(53)   = struct('spec_id','nonane_e','spec_name','','fbc_chemicalFormula','C9H20','fbc_charge',0);
			species(54)   = struct('spec_id','co_c','spec_name','','fbc_chemicalFormula','CO','fbc_charge',0);
			species(55)   = struct('spec_id','co_e','spec_name','','fbc_chemicalFormula','CO','fbc_charge',0);
			reactions(1) = struct('reac_id','ALCD3ir','equation','1 h_c + 1 ppal_c + 1 nadh_c = 1 nad_c + 1 ppoh_c','lb',0,'ub',0,'fbc_geneProductAssociation','E2348C_RS11505');
			reactions(2) = struct('reac_id','MMSAD2','equation','1 nad_c + 1 ppal_c + 1 coa_c = 1 h_c + 1 ppcoa_c + 1 nadh_c','lb',0,'ub',0,'fbc_geneProductAssociation','E2348C_RS11500');
			reactions(3) = struct('reac_id','PPOHtep','equation','1 ppoh_c = 1 ppoh_p','lb',0,'ub',0,'fbc_geneProductAssociation','');
			reactions(4) = struct('reac_id','PPOHtex','equation','1 ppoh_p = 1 ppoh_e','lb',0,'ub',0,'fbc_geneProductAssociation','');
			reactions(5) = struct('reac_id','EX_ppoh_e','equation','1 ppoh_e','lb',0,'ub',0,'fbc_geneProductAssociation','');
			reactions(6) = struct('reac_id','ETHGLYtep','equation','1 ethgly_c = 1 ethgly_p','lb',0,'ub',0,'fbc_geneProductAssociation','');
			reactions(7) = struct('reac_id','ETHGLYtex','equation','1 ethgly_p = 1 ethgly_e','lb',0,'ub',0,'fbc_geneProductAssociation','');
			reactions(8) = struct('reac_id','EX_ethgly_e','equation','1 ethgly_e','lb',0,'ub',0,'fbc_geneProductAssociation','');
			reactions(9) = struct('reac_id','ETHOXHYD','equation','1 h2o_c + 1 ethox_c = 1 ethgly_c','lb',0,'ub',0,'fbc_geneProductAssociation','epxh2');
			reactions(10) = struct('reac_id','EPOXD','equation','1 nad_c + 1 coa_c + 1 ethox_c = 1 h_c + 1 accoa_c + 1 nadh_c','lb',0,'ub',0,'fbc_geneProductAssociation','epxd');
			reactions(11) = struct('reac_id','ETHGLYRED','equation','1 nad_c + 1 ethgly_c = 1 h_c + 1 gcald_c + 1 nadh_c','lb',0,'ub',0,'fbc_geneProductAssociation','fucO');
			reactions(12) = struct('reac_id','FATB2Ch80','equation','1 ocACP_c + 1 h2o_c = 1 h_c + 1 octa_c + 1 ACP_c','lb',0,'ub',0,'fbc_geneProductAssociation','fatb2');
			reactions(13) = struct('reac_id','FATB2Ch100','equation','1 h2o_c + 1 dcaACP_c = 1 dca_c + 1 h_c + 1 ACP_c','lb',0,'ub',0,'fbc_geneProductAssociation','fatb2');
			reactions(14) = struct('reac_id','ACOATthl','equation','2 accoa_c = 1 aacoa_c + 1 coa_c','lb',0,'ub',0,'fbc_geneProductAssociation','thl');
			reactions(15) = struct('reac_id','PDH40','equation','1 nad_c + 1 2obut_c + 1 coa_c = 1 ppcoa_c + 1 nadh_c + 1 co2_c','lb',0,'ub',0,'fbc_geneProductAssociation','ado');
			reactions(16) = struct('reac_id','ADO40','equation','1 btal_c + 1 h2o_c = 1 h_c + 1 for_c + 1 propane_c','lb',0,'ub',0,'fbc_geneProductAssociation','ado');
			reactions(17) = struct('reac_id','ADO50','equation','1 h2o_c + 1 ptal_c = 1 h_c + 1 for_c + 1 butane_c','lb',-1000,'ub',1000,'fbc_geneProductAssociation','ado');
			reactions(18) = struct('reac_id','ADO60','equation','1 h2o_c + 1 hxal_c = 1 h_c + 1 for_c + 1 pentane_c','lb',0,'ub',0,'fbc_geneProductAssociation','ado');
			reactions(19) = struct('reac_id','ADO70','equation','1 h2o_c + 1 hptal_c = 1 h_c + 1 for_c + 1 hxane_c','lb',0,'ub',0,'fbc_geneProductAssociation','ado');
			reactions(20) = struct('reac_id','ADO80','equation','1 h2o_c + 1 octal_c = 1 h_c + 1 for_c + 1 heptane_c','lb',0,'ub',0,'fbc_geneProductAssociation','ado');
			reactions(21) = struct('reac_id','ADO90','equation','1 h2o_c + 1 nonal_c = 1 h_c + 1 for_c + 1 octane_c','lb',0,'ub',0,'fbc_geneProductAssociation','ado');
			reactions(22) = struct('reac_id','ADO100','equation','1 h2o_c + 1 dcal_c = 1 h_c + 1 for_c + 1 nonane_c','lb',0,'ub',0,'fbc_geneProductAssociation','ado');
			reactions(23) = struct('reac_id','CARNi4','equation','1 h_c + 1 atp_c + 1 but_c + 1 nadph_c = 1 btal_c + 1 ppi_c + 1 nadp_c + 1 amp_c','lb',0,'ub',0,'fbc_geneProductAssociation','car');
			reactions(24) = struct('reac_id','CARNi5','equation','1 h_c + 1 atp_c + 1 nadph_c + 1 val_c = 1 ppi_c + 1 nadp_c + 1 amp_c + 1 ptal_c','lb',-1000,'ub',1000,'fbc_geneProductAssociation','car');
			reactions(25) = struct('reac_id','CARNi6','equation','1 h_c + 1 atp_c + 1 hxa_c + 1 nadph_c = 1 ppi_c + 1 nadp_c + 1 amp_c + 1 hxal_c','lb',0,'ub',0,'fbc_geneProductAssociation','car');
			reactions(26) = struct('reac_id','CARNi7','equation','1 h_c + 1 atp_c + 1 nadph_c + 1 hpta_c = 1 ppi_c + 1 nadp_c + 1 amp_c + 1 hptal_c','lb',0,'ub',0,'fbc_geneProductAssociation','car');
			reactions(27) = struct('reac_id','CARNi9','equation','1 h_c + 1 atp_c + 1 nadph_c + 1 nonte_c = 1 ppi_c + 1 nadp_c + 1 amp_c + 1 nonal_c','lb',0,'ub',0,'fbc_geneProductAssociation','car');
			reactions(28) = struct('reac_id','CARNi10','equation','1 dca_c + 1 h_c + 1 atp_c + 1 nadph_c = 1 ppi_c + 1 nadp_c + 1 amp_c + 1 dcal_c','lb',0,'ub',0,'fbc_geneProductAssociation','car');
			reactions(29) = struct('reac_id','CARNi8','equation','1 h_c + 1 octa_c + 1 atp_c + 1 nadph_c = 1 ppi_c + 1 nadp_c + 1 amp_c + 1 octal_c','lb',0,'ub',0,'fbc_geneProductAssociation','car');
			reactions(30) = struct('reac_id','THSTRS4','equation','1 btcoa_c + 1 h2o_c = 1 h_c + 1 but_c + 1 coa_c','lb',0,'ub',0,'fbc_geneProductAssociation','tesB');
			reactions(31) = struct('reac_id','THSTRS5','equation','1 h2o_c + 1 ptcoa_c = 1 h_c + 1 coa_c + 1 val_c','lb',-1000,'ub',1000,'fbc_geneProductAssociation','tesB');
			reactions(32) = struct('reac_id','THSTRS6','equation','1 h2o_c + 1 hxcoa_c = 1 h_c + 1 hxa_c + 1 coa_c','lb',0,'ub',0,'fbc_geneProductAssociation','tesB');
			reactions(33) = struct('reac_id','THSTRS7','equation','1 h2o_c + 1 hptcoa_c = 1 h_c + 1 coa_c + 1 hpta_c','lb',0,'ub',0,'fbc_geneProductAssociation','tesB');
			reactions(34) = struct('reac_id','THSTRS9','equation','1 h2o_c + 1 noncoa_c = 1 h_c + 1 coa_c + 1 nonte_c','lb',0,'ub',0,'fbc_geneProductAssociation','tesB');
			reactions(35) = struct('reac_id','TERTD4','equation','1 h_c + 1 nadh_c + 1 cis23dhbtcoa_c = 1 nad_c + 1 btcoa_c','lb',-1000,'ub',1000,'fbc_geneProductAssociation','ter');
			reactions(36) = struct('reac_id','TERTD5','equation','1 h_c + 1 nadh_c + 1 cis2mctcoa_c = 1 nad_c + 1 ptcoa_c','lb',-1000,'ub',1000,'fbc_geneProductAssociation','ter');
			reactions(37) = struct('reac_id','TERTD6','equation','1 h_c + 1 nadh_c + 1 cis2hxncoa_c = 1 nad_c + 1 hxcoa_c','lb',0,'ub',0,'fbc_geneProductAssociation','ter');
			reactions(38) = struct('reac_id','TERTD7','equation','1 h_c + 1 nadh_c + 1 cis2hpcoa_c = 1 nad_c + 1 hptcoa_c','lb',0,'ub',0,'fbc_geneProductAssociation','ter');
			reactions(39) = struct('reac_id','TERTD9','equation','1 h_c + 1 nadh_c + 1 cis2noncoa_c = 1 nad_c + 1 noncoa_c','lb',0,'ub',0,'fbc_geneProductAssociation','ter');
			reactions(40) = struct('reac_id','PHAJ4B4','equation','1 3hbcoa__R_c = 1 h2o_c + 1 cis23dhbtcoa_c','lb',-1000,'ub',1000,'fbc_geneProductAssociation','phaJ4b');
			reactions(41) = struct('reac_id','PHAJ4B5','equation','1 3hptcoa_c = 1 h2o_c + 1 cis2mctcoa_c','lb',-1000,'ub',1000,'fbc_geneProductAssociation','phaJ4b');
			reactions(42) = struct('reac_id','PHAJ4B6','equation','1 3hhcoa__R_c = 1 h2o_c + 1 cis2hxncoa_c','lb',0,'ub',0,'fbc_geneProductAssociation','phaJ4b');
			reactions(43) = struct('reac_id','PHAJ4B7','equation','1 3hpcoa__R_c = 1 h2o_c + 1 cis2hpcoa_c','lb',0,'ub',0,'fbc_geneProductAssociation','phaJ4b');
			reactions(44) = struct('reac_id','PHAJ4B9','equation','1 3hnoncoa__R_c = 1 h2o_c + 1 cis2noncoa_c','lb',0,'ub',0,'fbc_geneProductAssociation','phaJ4b');
			reactions(45) = struct('reac_id','PHAB6','equation','1 h_c + 1 3ohcoa_c + 1 nadph_c = 1 nadp_c + 1 3hhcoa__R_c','lb',0,'ub',0,'fbc_geneProductAssociation','phaB');
			reactions(46) = struct('reac_id','PHAB5','equation','1 h_c + 1 nadph_c + 1 3oxptcoa_c = 1 nadp_c + 1 3hptcoa_c','lb',-1000,'ub',1000,'fbc_geneProductAssociation','phaB');
			reactions(47) = struct('reac_id','PHAB4','equation','1 h_c + 1 aacoa_c + 1 nadph_c = 1 nadp_c + 1 3hbcoa__R_c','lb',-1000,'ub',1000,'fbc_geneProductAssociation','phaB');
			reactions(48) = struct('reac_id','PHAB7','equation','1 h_c + 1 nadph_c + 1 3oxhepcoa_c = 1 nadp_c + 1 3hpcoa__R_c','lb',0,'ub',0,'fbc_geneProductAssociation','phaB');
			reactions(49) = struct('reac_id','PHAB9','equation','1 h_c + 1 nadph_c + 1 3ononcoa_c = 1 nadp_c + 1 3hnoncoa__R_c','lb',0,'ub',0,'fbc_geneProductAssociation','phaB');
			reactions(50) = struct('reac_id','BTKB6','equation','1 accoa_c + 1 btcoa_c = 1 3ohcoa_c + 1 coa_c','lb',0,'ub',0,'fbc_geneProductAssociation','bktB');
			reactions(51) = struct('reac_id','BTKB5','equation','1 accoa_c + 1 ppcoa_c = 1 coa_c + 1 3oxptcoa_c','lb',-1000,'ub',1000,'fbc_geneProductAssociation','bktB');
			reactions(52) = struct('reac_id','BTKB4','equation','2 accoa_c = 1 aacoa_c + 1 coa_c','lb',0,'ub',0,'fbc_geneProductAssociation','bktB');
			reactions(53) = struct('reac_id','BTKB7','equation','1 accoa_c + 1 ptcoa_c = 1 coa_c + 1 3oxhepcoa_c','lb',0,'ub',0,'fbc_geneProductAssociation','bktB');
			reactions(54) = struct('reac_id','BTKB9','equation','1 accoa_c + 1 hptcoa_c = 1 coa_c + 1 3ononcoa_c','lb',0,'ub',0,'fbc_geneProductAssociation','bktB');
			reactions(55) = struct('reac_id','HEXANEtex','equation','1 hxane_p = 1 hxane_e','lb',0,'ub',0,'fbc_geneProductAssociation','');
			reactions(56) = struct('reac_id','HEXANEtp','equation','1 hxane_c = 1 hxane_p','lb',0,'ub',0,'fbc_geneProductAssociation','');
			reactions(57) = struct('reac_id','PROPANEtp','equation','1 propane_c = 1 propane_p','lb',0,'ub',0,'fbc_geneProductAssociation','');
			reactions(58) = struct('reac_id','PROPANEtex','equation','1 propane_p = 1 propane_e','lb',0,'ub',0,'fbc_geneProductAssociation','');
			reactions(59) = struct('reac_id','BUTANEtp','equation','1 butane_c = 1 butane_p','lb',0,'ub',1000,'fbc_geneProductAssociation','');
			reactions(60) = struct('reac_id','BUTANEtex','equation','1 butane_p = 1 butane_e','lb',0,'ub',1000,'fbc_geneProductAssociation','');
			reactions(61) = struct('reac_id','PENTANEtp','equation','1 pentane_c = 1 pentane_p','lb',0,'ub',0,'fbc_geneProductAssociation','');
			reactions(62) = struct('reac_id','PENTANEtex','equation','1 pentane_p = 1 pentane_e','lb',0,'ub',0,'fbc_geneProductAssociation','');
			reactions(63) = struct('reac_id','HEPTANEtp','equation','1 heptane_c = 1 heptane_p','lb',0,'ub',0,'fbc_geneProductAssociation','');
			reactions(64) = struct('reac_id','HEPTANEtex','equation','1 heptane_p = 1 heptane_e','lb',0,'ub',0,'fbc_geneProductAssociation','');
			reactions(65) = struct('reac_id','OCTANEtp','equation','1 octane_c = 1 octane_p','lb',0,'ub',0,'fbc_geneProductAssociation','');
			reactions(66) = struct('reac_id','OCTANEtex','equation','1 octane_p = 1 octane_e','lb',0,'ub',0,'fbc_geneProductAssociation','');
			reactions(67) = struct('reac_id','NONANEtex','equation','1 nonane_p = 1 nonane_e','lb',0,'ub',0,'fbc_geneProductAssociation','');
			reactions(68) = struct('reac_id','NONANEtp','equation','1 nonane_c = 1 nonane_p','lb',0,'ub',0,'fbc_geneProductAssociation','');
			reactions(69) = struct('reac_id','cotp','equation','1 co_c = 1 co_e','lb',0,'ub',0,'fbc_geneProductAssociation','');
			reactions(70) = struct('reac_id','EX_co_e','equation','1 co_e','lb',0,'ub',0,'fbc_geneProductAssociation','');
			reactions(71) = struct('reac_id','EX_propane_e','equation','1 propane_e','lb',0,'ub',0,'fbc_geneProductAssociation','');
			reactions(72) = struct('reac_id','EX_butane_e','equation','1 butane_e','lb',0,'ub',1000,'fbc_geneProductAssociation','');
			reactions(73) = struct('reac_id','EX_pentane_e','equation','1 pentane_e','lb',0,'ub',0,'fbc_geneProductAssociation','');
			reactions(74) = struct('reac_id','EX_hexane_e','equation','1 hxane_e','lb',0,'ub',0,'fbc_geneProductAssociation','');
			reactions(75) = struct('reac_id','EX_heptane_e','equation','1 heptane_e','lb',0,'ub',0,'fbc_geneProductAssociation','');
			reactions(76) = struct('reac_id','EX_octane_e','equation','1 octane_e','lb',0,'ub',0,'fbc_geneProductAssociation','');
			reactions(77) = struct('reac_id','EX_nonane_e','equation','1 nonane_e','lb',0,'ub',0,'fbc_geneProductAssociation','');
        case 12 % methacrylic acid
			prod_id      = 'EX_2mp2e_e';
			species(1)   = struct('spec_id','2mppal_c','spec_name','2-Methylpropanal','fbc_chemicalFormula','C4H8O','fbc_charge',0);
			species(2)   = struct('spec_id','2mpp_c','spec_name','2-Methylpropanoate','fbc_chemicalFormula','C4H7O2','fbc_charge',-1);
			species(3)   = struct('spec_id','2mpcoa_c','spec_name','2-Methylpropanoly-CoA','fbc_chemicalFormula','C25H38N7O17P3S','fbc_charge',-4);
			species(4)   = struct('spec_id','2mp2coa_c','spec_name','2-Methylprop-2-enoyl-CoA','fbc_chemicalFormula','C25H36N7O17P3S','fbc_charge',-4);
			species(5)   = struct('spec_id','2mp2e_c','spec_name','2-Methylprop-2-enoic acid','fbc_chemicalFormula','C4H5O2','fbc_charge',-1);
			species(6)   = struct('spec_id','2mp2e_p','spec_name','2-Methylprop-2-enoic acid','fbc_chemicalFormula','C4H5O2','fbc_charge',-1);
			species(7)   = struct('spec_id','2mp2e_e','spec_name','2-Methylprop-2-enoic acid','fbc_chemicalFormula','C4H5O2','fbc_charge',-1);
			reactions(1) = struct('reac_id','3MOBDC','equation','1 3mob_c + 1 h_c = 1 co2_c + 1 2mppal_c','lb',0,'ub',1000,'fbc_geneProductAssociation','pdc_1_5_6');
			reactions(2) = struct('reac_id','2MPD','equation','1 2mppal_c + 1 nad_c + h2o_c = 1 2mpp_c + 2 h_c + 1 nadh_c','lb',0,'ub',1000,'fbc_geneProductAssociation','padA');
			reactions(3) = struct('reac_id','2MPCT','equation','1 2mpp_c + 1 accoa_c = 1 2mpcoa_c + 1 ac_c','lb',0,'ub',1000,'fbc_geneProductAssociation','pct');
			reactions(4) = struct('reac_id','BCDH','equation','1 3mob_c + 1 nad_c + coa_c = 1 2mpcoa_c + 1 co2_c + 1 nadh_c','lb',0,'ub',1000,'fbc_geneProductAssociation','bcdh');
			reactions(5) = struct('reac_id','SCDH','equation','1 fad_c + 2mpcoa_c = fadh2_c + 2mp2coa_c','lb',0,'ub',1000,'fbc_geneProductAssociation','acdH');
			reactions(6) = struct('reac_id','MTE','equation','1 h2o_c + 1 2mp2coa_c = 1 2mp2e_c + 1 coa_c + 1 h_c','lb',0,'ub',1000,'fbc_geneProductAssociation','fcbC');
			reactions(7) = struct('reac_id','2MP2Etpp','equation','1 2mp2e_c = 1 2mp2e_p','lb',-1000,'ub',1000,'fbc_geneProductAssociation','');
			reactions(8) = struct('reac_id','2MP2Etex','equation','1 2mp2e_p = 1 2mp2e_e','lb',0,'ub',1000,'fbc_geneProductAssociation','');
			reactions(9) = struct('reac_id','EX_2mp2e_e','equation','1 2mp2e_e =','lb',0,'ub',1000,'fbc_geneProductAssociation','');
        case 13 % resveratrol
			prod_id      = 'EX_revtl_e';
			species(1)   = struct('spec_id','cou_c','spec_name','4-coumarate','fbc_chemicalFormula','C9H7O3','fbc_charge',-1);
			species(2)   = struct('spec_id','coucoa_c','spec_name','4-coumaroyl-CoA','fbc_chemicalFormula','C30H38N7O18P3S','fbc_charge',-4);
			species(3)   = struct('spec_id','revtl_c','spec_name','trans-resveratrol','fbc_chemicalFormula','C14H12O3','fbc_charge',0);
			species(4)   = struct('spec_id','revtl_p','spec_name','trans-resveratrol (periplasm)','fbc_chemicalFormula','C14H12O3','fbc_charge',0);
			species(5)   = struct('spec_id','revtl_e','spec_name','trans-resveratrol (extracellular)','fbc_chemicalFormula','C14H12O3','fbc_charge',0);
			reactions(1) = struct('reac_id','TAL','equation','tyr__L_c = nh4_c + cou_c','lb',0,'ub',1000,'fbc_geneProductAssociation','pal');
			reactions(2) = struct('reac_id','CCL','equation','1 cou_c + 1 atp_c + 1 coa_c = 1 coucoa_c + 1 amp_c + 1 ppi_c','lb',0,'ub',1000,'fbc_geneProductAssociation','couB');
			reactions(3) = struct('reac_id','STS','equation','3 malcoa_c + coucoa_c + 3 h_c = 4 coa_c + revtl_c + 4 co2_c','lb',0,'ub',1000,'fbc_geneProductAssociation','sts');
			reactions(4) = struct('reac_id','REVTLtpp','equation','1 revtl_c = 1 revtl_p','lb',0,'ub',1000,'fbc_geneProductAssociation','');
			reactions(5) = struct('reac_id','REVTLtex','equation','1 revtl_p = 1 revtl_e','lb',0,'ub',1000,'fbc_geneProductAssociation','');
			reactions(6) = struct('reac_id','EX_revtl_e','equation','1 revtl_e =','lb',0,'ub',1000,'fbc_geneProductAssociation','');
			reactions(7) = struct('reac_id','XPK','equation','1 xu5p__D_c + 1 pi_c = 1 actp_c + 1 g3p_c + 1 h2o_c','lb',0,'ub',1000,'fbc_geneProductAssociation','fxpk');
			reactions(8) = struct('reac_id','FPK','equation','1 f6p_c + 1 pi_c = 1 actp_c + 1 e4p_c + 1 h2o_c','lb',0,'ub',1000,'fbc_geneProductAssociation','fxpk');
        case 14 % bisabolene
			prod_id      = 'EX_bsb_e';
			species(1)   = struct('spec_id','hmgcoa_c','spec_name','3-Hydroxy-3-methyl-glutaryl-CoA','fbc_chemicalFormula','C27H39N7O20P3S','fbc_charge',-5);
			species(2)   = struct('spec_id','mev_c','spec_name','(3R)-3,5-Dihydroxy-3-methylpentanoate','fbc_chemicalFormula','C6H11O4','fbc_charge',-1);
			species(3)   = struct('spec_id','5pmev_c','spec_name','(3R)-3-Hydroxy-3-methyl-5-(phosphonooxy)pentanoate','fbc_chemicalFormula','C6H10O7P','fbc_charge',-3);
			species(4)   = struct('spec_id','5dpmev_c','spec_name','(3R)-3-Hydroxy-5-{[hydroxy(phosphonooxy)phosphoryl]oxy}-3-methylpentanoate','fbc_chemicalFormula','C6H10O10P2','fbc_charge',-4);
			species(5)   = struct('spec_id','bsb_c','spec_name','bisaboleme','fbc_chemicalFormula','C15H24','fbc_charge',0);
			species(6)   = struct('spec_id','bsb_p','spec_name','bisaboleme (periplasm)','fbc_chemicalFormula','C15H24','fbc_charge',0);
			species(7)   = struct('spec_id','bsb_e','spec_name','bisaboleme (extracellular)','fbc_chemicalFormula','C15H24','fbc_charge',0);
			reactions(1) = struct('reac_id','HMGCOAS','equation','1 aacoa_c + 1 accoa_c + 1 h2o_c = 1 coa_c + 1 h_c + 1 hmgcoa_c','lb',-1000,'ub',1000,'fbc_geneProductAssociation','mep');
			reactions(2) = struct('reac_id','HMGCOAR','equation','2 h_c + 2 nadph_c + 1 hmgcoa_c = 1 coa_c + 2 nadp_c + 1 mev_c','lb',-1000,'ub',1000,'fbc_geneProductAssociation','mep');
			reactions(3) = struct('reac_id','MEVK1','equation','1 atp_c + 1 mev_c = 1 adp_c + 1 h_c + 1 5pmev_c','lb',0,'ub',1000,'fbc_geneProductAssociation','mep');
			reactions(4) = struct('reac_id','PMEVK','equation','1 atp_c + 1 5pmev_c = 1 adp_c + 1 5dpmev_c','lb',0,'ub',1000,'fbc_geneProductAssociation','mep');
			reactions(5) = struct('reac_id','DPMVD','equation','1 atp_c + 1 5dpmev_c = 1 adp_c + 1 co2_c + 1 ipdp_c + 1 pi_c','lb',0,'ub',1000,'fbc_geneProductAssociation','mep');
			reactions(6) = struct('reac_id','FPPS','equation','2 ipdp_c + 1 dmpp_c = frdp_c + 2 ppi_c','lb',0,'ub',1000,'fbc_geneProductAssociation','ispA');
			reactions(7) = struct('reac_id','BSBS','equation','1 frdp_c = 1 bsb_c + 1 ppi_c','lb',0,'ub',1000,'fbc_geneProductAssociation','ag1');
			reactions(8) = struct('reac_id','BSBtpp','equation','1 bsb_c = 1 bsb_p','lb',-1000,'ub',1000,'fbc_geneProductAssociation','');
			reactions(9) = struct('reac_id','BSBtex','equation','1 bsb_p = 1 bsb_e','lb',-1000,'ub',1000,'fbc_geneProductAssociation','');
			reactions(10) = struct('reac_id','EX_bsb_e','equation','1 bsb_e =','lb',0,'ub',1000,'fbc_geneProductAssociation','');
			reactions(11) = struct('reac_id','XPK','equation','1 xu5p__D_c + 1 pi_c = 1 actp_c + 1 g3p_c + 1 h2o_c','lb',0,'ub',1000,'fbc_geneProductAssociation','fxpk');
			reactions(12) = struct('reac_id','FPK','equation','1 f6p_c + 1 pi_c = 1 actp_c + 1 e4p_c + 1 h2o_c','lb',0,'ub',1000,'fbc_geneProductAssociation','fxpk');
        case 15 % 4-hydroxycoumarin
			prod_id      = 'EX_4hc_e';
			species(1)   = struct('spec_id','salc_c','spec_name','salicylate','fbc_chemicalFormula','C7H5O3','fbc_charge',-1);
			species(2)   = struct('spec_id','salccoa_c','spec_name','salicyl-CoA, 2-Hydroxybenzoyl-CoA','fbc_chemicalFormula','C28H36N7O18P3S','fbc_charge',-4);
			species(3)   = struct('spec_id','4hc_c','spec_name','4-hydroxycoumarin','fbc_chemicalFormula','C9H6O3','fbc_charge',0);
			species(4)   = struct('spec_id','4hc_p','spec_name','4-hydroxycoumarin (periplasm)','fbc_chemicalFormula','C9H6O3','fbc_charge',0);
			species(5)   = struct('spec_id','4hc_e','spec_name','4-hydroxycoumarin (extracellular)','fbc_chemicalFormula','C9H6O3','fbc_charge',0);
			reactions(1) = struct('reac_id','IPL','equation','ichor_c = pyr_c + salc_c','lb',0,'ub',1000,'fbc_geneProductAssociation','pchB');
			reactions(2) = struct('reac_id','SCL','equation','salc_c + coa_c + atp_c = salccoa_c + amp_c + ppi_c','lb',0,'ub',1000,'fbc_geneProductAssociation','sdgA');
			reactions(3) = struct('reac_id','BIS','equation','salccoa_c + h_c + malcoa_c = 4hc_c + co2_c + 2 coa_c','lb',0,'ub',1000,'fbc_geneProductAssociation','pqsD');
			reactions(4) = struct('reac_id','4HCtpp','equation','1 4hc_c = 1 4hc_p','lb',0,'ub',1000,'fbc_geneProductAssociation','');
			reactions(5) = struct('reac_id','4HCtex','equation','1 4hc_p = 1 4hc_e','lb',0,'ub',1000,'fbc_geneProductAssociation','');
			reactions(6) = struct('reac_id','EX_4hc_e','equation','1 4hc_e =','lb',0,'ub',1000,'fbc_geneProductAssociation','');
			reactions(7) = struct('reac_id','XPK','equation','1 xu5p__D_c + 1 pi_c = 1 actp_c + 1 g3p_c + 1 h2o_c','lb',0,'ub',1000,'fbc_geneProductAssociation','fxpk');
			reactions(8) = struct('reac_id','FPK','equation','1 f6p_c + 1 pi_c = 1 actp_c + 1 e4p_c + 1 h2o_c','lb',0,'ub',1000,'fbc_geneProductAssociation','fxpk');
    end
end

